<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Defaults\Colours.xml" />
    <None Remove="Resources\Defaults\Frames.xml" />
    <None Remove="Styles\DefaultStyleImage.png" />
    <None Remove="Styles\Styles.xml" />
    <None Remove="Templates\Defaults\Buttons.xml" />
    <None Remove="Templates\Defaults\Partitions.xml" />
    <None Remove="Templates\Defaults\Sliders.xml" />
    <None Remove="Templates\Templates.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Defaults\Colours.xml" />
    <EmbeddedResource Include="Resources\Defaults\Frames.xml" />
    <EmbeddedResource Include="Resources\DefaultGuiSpritesheet.png" />
    <EmbeddedResource Include="Styles\Defaults\Labels.xml" />
    <EmbeddedResource Include="Styles\Defaults\Buttons.xml" />
    <EmbeddedResource Include="Styles\Defaults\Partitions.xml" />
    <EmbeddedResource Include="Templates\Defaults\Buttons.xml" />
    <EmbeddedResource Include="Templates\Defaults\Partitions.xml" />
    <EmbeddedResource Include="Templates\Defaults\Sliders.xml" />
    <EmbeddedResource Include="Templates\Defaults\Labels.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lovebirb.LiruGameHelper" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
  </ItemGroup>

</Project>
